//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryGuessWho.Properties.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibraryGuessWho.Properties.Localization.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUESS WHO?.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string BtnCreateAccount {
            get {
                return ResourceManager.GetString("BtnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend code.
        /// </summary>
        public static string BtnResendCode {
            get {
                return ResourceManager.GetString("BtnResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        public static string BtnVerifyCode {
            get {
                return ResourceManager.GetString("BtnVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Passwords.
        /// </summary>
        public static string chkShowPasswords {
            get {
                return ResourceManager.GetString("chkShowPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you are trying to find or add does not exist..
        /// </summary>
        public static string CODE_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CODE_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already friends with this user..
        /// </summary>
        public static string CODE_ALREADY_FRIENDS {
            get {
                return ResourceManager.GetString("CODE_ALREADY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected avatar is currently unavailable..
        /// </summary>
        public static string CODE_AVATAR_INVALID {
            get {
                return ResourceManager.GetString("CODE_AVATAR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot send a friend request to yourself..
        /// </summary>
        public static string CODE_CANNOT_FRIEND_SELF {
            get {
                return ResourceManager.GetString("CODE_CANNOT_FRIEND_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password entered is incorrect..
        /// </summary>
        public static string CODE_CURRENT_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("CODE_CURRENT_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter your current password to confirm changes..
        /// </summary>
        public static string CODE_CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user you are trying to contact is currently inactive..
        /// </summary>
        public static string CODE_DESTINATION_INACTIVE {
            get {
                return ResourceManager.GetString("CODE_DESTINATION_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The display name does not meet the system requirements..
        /// </summary>
        public static string CODE_DISPLAYNAME_INVALID {
            get {
                return ResourceManager.GetString("CODE_DISPLAYNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The provided account identifier is invalid..
        /// </summary>
        public static string CODE_INVALID_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("CODE_INVALID_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The display name has an incorrect format..
        /// </summary>
        public static string CODE_INVALID_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("CODE_INVALID_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user identifiers do not match..
        /// </summary>
        public static string CODE_INVALID_IDS {
            get {
                return ResourceManager.GetString("CODE_INVALID_IDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No changes were detected to be saved..
        /// </summary>
        public static string CODE_NO_CHANGES_PROVIDED {
            get {
                return ResourceManager.GetString("CODE_NO_CHANGES_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have permission to perform this action..
        /// </summary>
        public static string CODE_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("CODE_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The requested friendship record was not found..
        /// </summary>
        public static string CODE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CODE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This request is no longer pending approval..
        /// </summary>
        public static string CODE_NOT_PENDING {
            get {
                return ResourceManager.GetString("CODE_NOT_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not delete the account. Please try again later..
        /// </summary>
        public static string CODE_PROFILE_DELETE_FAILED {
            get {
                return ResourceManager.GetString("CODE_PROFILE_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user profile information could not be found..
        /// </summary>
        public static string CODE_PROFILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CODE_PROFILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A friend request is already pending with this user..
        /// </summary>
        public static string CODE_REQUEST_ALREADY_PENDING {
            get {
                return ResourceManager.GetString("CODE_REQUEST_ALREADY_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while generating the request. Please try again..
        /// </summary>
        public static string CODE_REQUEST_ID_NOT_GENERATED {
            get {
                return ResourceManager.GetString("CODE_REQUEST_ID_NOT_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request is empty or invalid..
        /// </summary>
        public static string CODE_REQUEST_NULL {
            get {
                return ResourceManager.GetString("CODE_REQUEST_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal error occurred while saving profile changes..
        /// </summary>
        public static string CODE_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("CODE_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user session is invalid or has expired..
        /// </summary>
        public static string CODE_USER_ID_INVALID {
            get {
                return ResourceManager.GetString("CODE_USER_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to connect to the database.
        /// </summary>
        public static string FaultDatabaseConnection {
            get {
                return ResourceManager.GetString("FaultDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The database server took too long to respond.
        /// </summary>
        public static string FaultDatabaseTimeout {
            get {
                return ResourceManager.GetString("FaultDatabaseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email address is already registered.
        /// </summary>
        public static string FaultDuplicateEmail {
            get {
                return ResourceManager.GetString("FaultDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The operation violates an existing relationship.
        /// </summary>
        public static string FaultForeignKey {
            get {
                return ResourceManager.GetString("FaultForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request is invalid.
        /// </summary>
        public static string FaultInvalidRequest {
            get {
                return ResourceManager.GetString("FaultInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred.
        /// </summary>
        public static string FaultUnexpected {
            get {
                return ResourceManager.GetString("FaultUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account not found or inactive.
        /// </summary>
        public static string FRIEND_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("FRIEND_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This user is already your friend..
        /// </summary>
        public static string FRIEND_ALREADY_FRIENDS {
            get {
                return ResourceManager.GetString("FRIEND_ALREADY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot add yourself as a friend.
        /// </summary>
        public static string FRIEND_CANNOT_SELF {
            get {
                return ResourceManager.GetString("FRIEND_CANNOT_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid account ID.
        /// </summary>
        public static string FRIEND_INVALID_ACCOUNT_ID {
            get {
                return ResourceManager.GetString("FRIEND_INVALID_ACCOUNT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A pending request already exists..
        /// </summary>
        public static string FRIEND_REQUEST_ALREADY_PENDING {
            get {
                return ResourceManager.GetString("FRIEND_REQUEST_ALREADY_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request cannot be null..
        /// </summary>
        public static string FRIEND_REQUEST_NULL {
            get {
                return ResourceManager.GetString("FRIEND_REQUEST_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected error in friend system..
        /// </summary>
        public static string FRIEND_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("FRIEND_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string FriendErrorTitle {
            get {
                return ResourceManager.GetString("FriendErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent successfully!.
        /// </summary>
        public static string FriendRequestSent {
            get {
                return ResourceManager.GetString("FriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string LblUser {
            get {
                return ResourceManager.GetString("LblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string LblVerificationCode {
            get {
                return ResourceManager.GetString("LblVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string LinkCreate {
            get {
                return ResourceManager.GetString("LinkCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I forgot my password.
        /// </summary>
        public static string LinkForgot {
            get {
                return ResourceManager.GetString("LinkForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account is locked. Please contact support..
        /// </summary>
        public static string LoginAccountLocked {
            get {
                return ResourceManager.GetString("LoginAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login error.
        /// </summary>
        public static string LoginErrorTitle {
            get {
                return ResourceManager.GetString("LoginErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email or password..
        /// </summary>
        public static string LoginInvalidCredentials {
            get {
                return ResourceManager.GetString("LoginInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t start your session. Please try again..
        /// </summary>
        public static string LoginProfileActivationFailed {
            get {
                return ResourceManager.GetString("LoginProfileActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string LoginWelcomeTitle {
            get {
                return ResourceManager.GetString("LoginWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password does not meet security requirements..
        /// </summary>
        public static string ODE_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("ODE_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created.
        /// </summary>
        public static string UiAccountCreatedForFmt {
            get {
                return ResourceManager.GetString("UiAccountCreatedForFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not communicate with the service.
        /// </summary>
        public static string UiCommsGeneric {
            get {
                return ResourceManager.GetString("UiCommsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong. Please try again..
        /// </summary>
        public static string UiGenericError {
            get {
                return ResourceManager.GetString("UiGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This action can&apos;t be completed right now. Please try again..
        /// </summary>
        public static string UiInvalidOperation {
            get {
                return ResourceManager.GetString("UiInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can resend the code in {0} seconds.
        /// </summary>
        public static string UiResendInFmt {
            get {
                return ResourceManager.GetString("UiResendInFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A security error occurred while connecting. Please try again..
        /// </summary>
        public static string UiSecurityError {
            get {
                return ResourceManager.GetString("UiSecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transport authentication (Windows) failed. Verify that the service is running.
        /// </summary>
        public static string UiSecurityNegotiationFailed {
            get {
                return ResourceManager.GetString("UiSecurityNegotiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The service is unavailable. Please try again later..
        /// </summary>
        public static string UiServiceUnavailable {
            get {
                return ResourceManager.GetString("UiServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request timed out. Please try again..
        /// </summary>
        public static string UiTimeout {
            get {
                return ResourceManager.GetString("UiTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string UiTitleError {
            get {
                return ResourceManager.GetString("UiTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string UiTitleInfo {
            get {
                return ResourceManager.GetString("UiTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string UiTitleWarning {
            get {
                return ResourceManager.GetString("UiTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display name is required.
        /// </summary>
        public static string UiValidationDisplayNameRequired {
            get {
                return ResourceManager.GetString("UiValidationDisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display name is too long (max. 50 characteres).
        /// </summary>
        public static string UiValidationDisplayNameTooLong {
            get {
                return ResourceManager.GetString("UiValidationDisplayNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email format.
        /// </summary>
        public static string UiValidationEmailFormat {
            get {
                return ResourceManager.GetString("UiValidationEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required.
        /// </summary>
        public static string UiValidationEmailRequired {
            get {
                return ResourceManager.GetString("UiValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string UiValidationPasswordDontMatch {
            get {
                return ResourceManager.GetString("UiValidationPasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required.
        /// </summary>
        public static string UiValidationPasswordRequired {
            get {
                return ResourceManager.GetString("UiValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be at least 8 characters long.
        /// </summary>
        public static string UiValidationPasswordTooShort {
            get {
                return ResourceManager.GetString("UiValidationPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A value is out of range. Please check your input..
        /// </summary>
        public static string UiValueOutOfRange {
            get {
                return ResourceManager.GetString("UiValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code has expired.
        /// </summary>
        public static string UIVerificationCodeExpired {
            get {
                return ResourceManager.GetString("UIVerificationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code is not valid.
        /// </summary>
        public static string UIVerificationCodeInvalid {
            get {
                return ResourceManager.GetString("UIVerificationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the verification code.
        /// </summary>
        public static string UIVerificationCodeRequired {
            get {
                return ResourceManager.GetString("UIVerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent a new verification code to your email.
        /// </summary>
        public static string UIVerificationResent {
            get {
                return ResourceManager.GetString("UIVerificationResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent a verification code to your email: {0}.
        /// </summary>
        public static string UiVerificationSentFmt {
            get {
                return ResourceManager.GetString("UiVerificationSentFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your email has been successfully verified.
        /// </summary>
        public static string UIVerificationSuccess {
            get {
                return ResourceManager.GetString("UIVerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration data is missing. Please fill in the form and try again..
        /// </summary>
        public static string USER_REQUEST_NULL {
            get {
                return ResourceManager.GetString("USER_REQUEST_NULL", resourceCulture);
            }
        }
    }
}
