//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.FriendServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendServiceRef.IFriendService")]
    public interface IFriendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SearchProfiles", ReplyAction="http://tempuri.org/IFriendService/SearchProfilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/SearchProfilesServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.SearchProfilesResponse SearchProfiles(GuessWhoCore.Contracts.Requests.SearchProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SearchProfiles", ReplyAction="http://tempuri.org/IFriendService/SearchProfilesResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.SearchProfilesResponse> SearchProfilesAsync(GuessWhoCore.Contracts.Requests.SearchProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/SendFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.SendFriendRequestResponse SendFriendRequest(GuessWhoCore.Contracts.Requests.SendFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.SendFriendRequestResponse> SendFriendRequestAsync(GuessWhoCore.Contracts.Requests.SendFriendRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendService/AcceptFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/AcceptFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse AcceptFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendService/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AcceptFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendService/RejectFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/RejectFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse RejectFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendService/RejectFriendRequestResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> RejectFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendService/CancelFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/CancelFriendRequestServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse CancelFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendService/CancelFriendRequestResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> CancelFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/GetFriendsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.GetFriendsResponse GetFriends(GuessWhoCore.Contracts.Requests.GetFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetFriendsResponse> GetFriendsAsync(GuessWhoCore.Contracts.Requests.GetFriendsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendService/GetPendingRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IFriendService/GetPendingRequestsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.GetPendingRequestsResponse GetPendingRequests(GuessWhoCore.Contracts.Requests.GetPendingFriendRequestsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendService/GetPendingRequestsResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetPendingRequestsResponse> GetPendingRequestsAsync(GuessWhoCore.Contracts.Requests.GetPendingFriendRequestsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendServiceChannel : GuessWhoClient.FriendServiceRef.IFriendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendServiceClient : System.ServiceModel.ClientBase<GuessWhoClient.FriendServiceRef.IFriendService>, GuessWhoClient.FriendServiceRef.IFriendService {
        
        public FriendServiceClient() {
        }
        
        public FriendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.SearchProfilesResponse SearchProfiles(GuessWhoCore.Contracts.Requests.SearchProfileRequest request) {
            return base.Channel.SearchProfiles(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.SearchProfilesResponse> SearchProfilesAsync(GuessWhoCore.Contracts.Requests.SearchProfileRequest request) {
            return base.Channel.SearchProfilesAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.SendFriendRequestResponse SendFriendRequest(GuessWhoCore.Contracts.Requests.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequest(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.SendFriendRequestResponse> SendFriendRequestAsync(GuessWhoCore.Contracts.Requests.SendFriendRequestRequest request) {
            return base.Channel.SendFriendRequestAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse AcceptFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.AcceptFriendRequest(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AcceptFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.AcceptFriendRequestAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse RejectFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.RejectFriendRequest(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> RejectFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.RejectFriendRequestAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse CancelFriendRequest(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.CancelFriendRequest(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> CancelFriendRequestAsync(GuessWhoCore.Contracts.Requests.FriendRequestOperationRequest request) {
            return base.Channel.CancelFriendRequestAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.GetFriendsResponse GetFriends(GuessWhoCore.Contracts.Requests.GetFriendsRequest request) {
            return base.Channel.GetFriends(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetFriendsResponse> GetFriendsAsync(GuessWhoCore.Contracts.Requests.GetFriendsRequest request) {
            return base.Channel.GetFriendsAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.GetPendingRequestsResponse GetPendingRequests(GuessWhoCore.Contracts.Requests.GetPendingFriendRequestsRequest request) {
            return base.Channel.GetPendingRequests(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetPendingRequestsResponse> GetPendingRequestsAsync(GuessWhoCore.Contracts.Requests.GetPendingFriendRequestsRequest request) {
            return base.Channel.GetPendingRequestsAsync(request);
        }
    }
}
