//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.LoginServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServiceRef.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/ILoginService/LoginUserServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.LoginResponse LoginUser(GuessWhoCore.Contracts.Requests.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.LoginResponse> LoginUserAsync(GuessWhoCore.Contracts.Requests.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LogoutUser", ReplyAction="http://tempuri.org/ILoginService/LogoutUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/ILoginService/LogoutUserServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse LogoutUser(GuessWhoCore.Contracts.Request.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LogoutUser", ReplyAction="http://tempuri.org/ILoginService/LogoutUserResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> LogoutUserAsync(GuessWhoCore.Contracts.Request.LogoutRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : GuessWhoClient.LoginServiceRef.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<GuessWhoClient.LoginServiceRef.ILoginService>, GuessWhoClient.LoginServiceRef.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.LoginResponse LoginUser(GuessWhoCore.Contracts.Requests.LoginRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.LoginResponse> LoginUserAsync(GuessWhoCore.Contracts.Requests.LoginRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse LogoutUser(GuessWhoCore.Contracts.Request.LogoutRequest request) {
            return base.Channel.LogoutUser(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> LogoutUserAsync(GuessWhoCore.Contracts.Request.LogoutRequest request) {
            return base.Channel.LogoutUserAsync(request);
        }
    }
}
