//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.LeaderboardServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeaderboardServiceRef.ILeaderboardService")]
    public interface ILeaderboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboardServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.GetLeaderboardResponse GetGlobalLeaderboard(GuessWhoCore.Contracts.Requests.GetLeaderboardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboardResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetLeaderboardResponse> GetGlobalLeaderboardAsync(GuessWhoCore.Contracts.Requests.GetLeaderboardRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeaderboardServiceChannel : GuessWhoClient.LeaderboardServiceRef.ILeaderboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeaderboardServiceClient : System.ServiceModel.ClientBase<GuessWhoClient.LeaderboardServiceRef.ILeaderboardService>, GuessWhoClient.LeaderboardServiceRef.ILeaderboardService {
        
        public LeaderboardServiceClient() {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.GetLeaderboardResponse GetGlobalLeaderboard(GuessWhoCore.Contracts.Requests.GetLeaderboardRequest request) {
            return base.Channel.GetGlobalLeaderboard(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetLeaderboardResponse> GetGlobalLeaderboardAsync(GuessWhoCore.Contracts.Requests.GetLeaderboardRequest request) {
            return base.Channel.GetGlobalLeaderboardAsync(request);
        }
    }
}
