//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.MatchServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchServiceRef.IMatchService", CallbackContract=typeof(GuessWhoClient.MatchServiceRef.IMatchServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/CreateMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/CreateMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/CreateMatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.CreateMatchResponse CreateMatch(GuessWhoCore.Contracts.Requests.CreateMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/CreateMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/CreateMatchResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.CreateMatchResponse> CreateMatchAsync(GuessWhoCore.Contracts.Requests.CreateMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/JoinMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/JoinMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/JoinMatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Requests.JoinMatchResponse JoinMatch(GuessWhoCore.Contracts.Requests.JoinMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/JoinMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/JoinMatchResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Requests.JoinMatchResponse> JoinMatchAsync(GuessWhoCore.Contracts.Requests.JoinMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/LeaveMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/LeaveMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/LeaveMatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse LeaveMatch(GuessWhoCore.Contracts.Requests.LeaveMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/LeaveMatch", ReplyAction="http://tempuri.org/IMatchLobbyOperations/LeaveMatchResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> LeaveMatchAsync(GuessWhoCore.Contracts.Requests.LeaveMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/SetPlayerReadyStatus", ReplyAction="http://tempuri.org/IMatchLobbyOperations/SetPlayerReadyStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/SetPlayerReadyStatusServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse SetPlayerReadyStatus(GuessWhoCore.Contracts.Requests.SetPlayerReadyStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/SetPlayerReadyStatus", ReplyAction="http://tempuri.org/IMatchLobbyOperations/SetPlayerReadyStatusResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> SetPlayerReadyStatusAsync(GuessWhoCore.Contracts.Requests.SetPlayerReadyStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/SubscribeLobby", ReplyAction="http://tempuri.org/IMatchLobbyOperations/SubscribeLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/SubscribeLobbyServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse SubscribeLobby(GuessWhoCore.Contracts.Requests.SubscribeLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/SubscribeLobby", ReplyAction="http://tempuri.org/IMatchLobbyOperations/SubscribeLobbyResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> SubscribeLobbyAsync(GuessWhoCore.Contracts.Requests.SubscribeLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/UnsubscribeLobby", ReplyAction="http://tempuri.org/IMatchLobbyOperations/UnsubscribeLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchLobbyOperations/UnsubscribeLobbyServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse UnsubscribeLobby(GuessWhoCore.Contracts.Requests.UnsubscribeLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchLobbyOperations/UnsubscribeLobby", ReplyAction="http://tempuri.org/IMatchLobbyOperations/UnsubscribeLobbyResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> UnsubscribeLobbyAsync(GuessWhoCore.Contracts.Requests.UnsubscribeLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/StartMatch", ReplyAction="http://tempuri.org/IMatchGameplayOperations/StartMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/StartMatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse StartMatch(GuessWhoCore.Contracts.Requests.StartMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/StartMatch", ReplyAction="http://tempuri.org/IMatchGameplayOperations/StartMatchResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> StartMatchAsync(GuessWhoCore.Contracts.Requests.StartMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/EndMatch", ReplyAction="http://tempuri.org/IMatchGameplayOperations/EndMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/EndMatchServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse EndMatch(GuessWhoCore.Contracts.Requests.EndMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/EndMatch", ReplyAction="http://tempuri.org/IMatchGameplayOperations/EndMatchResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> EndMatchAsync(GuessWhoCore.Contracts.Requests.EndMatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/ChooseSecretCharacter", ReplyAction="http://tempuri.org/IMatchGameplayOperations/ChooseSecretCharacterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/ChooseSecretCharacterServiceFaultFaul" +
            "t", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse ChooseSecretCharacter(GuessWhoCore.Contracts.Requests.ChooseSecretCharacterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/ChooseSecretCharacter", ReplyAction="http://tempuri.org/IMatchGameplayOperations/ChooseSecretCharacterResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> ChooseSecretCharacterAsync(GuessWhoCore.Contracts.Requests.ChooseSecretCharacterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/GetMatchDeck", ReplyAction="http://tempuri.org/IMatchGameplayOperations/GetMatchDeckResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/GetMatchDeckServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.MatchDeckResponse GetMatchDeck(GuessWhoCore.Contracts.Requests.GetOrCreateMatchDeckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/GetMatchDeck", ReplyAction="http://tempuri.org/IMatchGameplayOperations/GetMatchDeckResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.MatchDeckResponse> GetMatchDeckAsync(GuessWhoCore.Contracts.Requests.GetOrCreateMatchDeckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/AskQuestion", ReplyAction="http://tempuri.org/IMatchGameplayOperations/AskQuestionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/AskQuestionServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse AskQuestion(GuessWhoCore.Contracts.Requests.AskQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/AskQuestion", ReplyAction="http://tempuri.org/IMatchGameplayOperations/AskQuestionResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AskQuestionAsync(GuessWhoCore.Contracts.Requests.AskQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/AnswerQuestion", ReplyAction="http://tempuri.org/IMatchGameplayOperations/AnswerQuestionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/AnswerQuestionServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse AnswerQuestion(GuessWhoCore.Contracts.Requests.AnswerQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/AnswerQuestion", ReplyAction="http://tempuri.org/IMatchGameplayOperations/AnswerQuestionResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AnswerQuestionAsync(GuessWhoCore.Contracts.Requests.AnswerQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/PassTurn", ReplyAction="http://tempuri.org/IMatchGameplayOperations/PassTurnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/PassTurnServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.PassTurnResponse PassTurn(GuessWhoCore.Contracts.Requests.PassTurnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/PassTurn", ReplyAction="http://tempuri.org/IMatchGameplayOperations/PassTurnResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.PassTurnResponse> PassTurnAsync(GuessWhoCore.Contracts.Requests.PassTurnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/ClaimTimeout", ReplyAction="http://tempuri.org/IMatchGameplayOperations/ClaimTimeoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/ClaimTimeoutServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.ClaimTimeoutResponse ClaimTimeout(GuessWhoCore.Contracts.Requests.ClaimTimeoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/ClaimTimeout", ReplyAction="http://tempuri.org/IMatchGameplayOperations/ClaimTimeoutResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.ClaimTimeoutResponse> ClaimTimeoutAsync(GuessWhoCore.Contracts.Requests.ClaimTimeoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/FinalGuess", ReplyAction="http://tempuri.org/IMatchGameplayOperations/FinalGuessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IMatchGameplayOperations/FinalGuessServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.FinalGuessResponse FinalGuess(GuessWhoCore.Contracts.Requests.FinalGuessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchGameplayOperations/FinalGuess", ReplyAction="http://tempuri.org/IMatchGameplayOperations/FinalGuessResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.FinalGuessResponse> FinalGuessAsync(GuessWhoCore.Contracts.Requests.FinalGuessRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnPlayerJoined")]
        void OnPlayerJoined(GuessWhoCore.Contracts.Response.LobbyPlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnPlayerLeft")]
        void OnPlayerLeft(GuessWhoCore.Contracts.Response.LobbyPlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnReadyChanged")]
        void OnReadyChanged(GuessWhoCore.Contracts.Response.LobbyPlayerDto player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnSecretCharacterChosen")]
        void OnSecretCharacterChosen(long matchId, long userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnAllSecretCharactersChosen")]
        void OnAllSecretCharactersChosen(long matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnGameStarted")]
        void OnGameStarted(long matchId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnGameEnded")]
        void OnGameEnded(long matchId, long winnerUserId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnQuestionAsked")]
        void OnQuestionAsked(long matchId, long askingUserId, long attributeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnQuestionAnswered")]
        void OnQuestionAnswered(long matchId, long answeringUserId, int answerOptionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : GuessWhoClient.MatchServiceRef.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.DuplexClientBase<GuessWhoClient.MatchServiceRef.IMatchService>, GuessWhoClient.MatchServiceRef.IMatchService {
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.CreateMatchResponse CreateMatch(GuessWhoCore.Contracts.Requests.CreateMatchRequest request) {
            return base.Channel.CreateMatch(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.CreateMatchResponse> CreateMatchAsync(GuessWhoCore.Contracts.Requests.CreateMatchRequest request) {
            return base.Channel.CreateMatchAsync(request);
        }
        
        public GuessWhoCore.Contracts.Requests.JoinMatchResponse JoinMatch(GuessWhoCore.Contracts.Requests.JoinMatchRequest request) {
            return base.Channel.JoinMatch(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Requests.JoinMatchResponse> JoinMatchAsync(GuessWhoCore.Contracts.Requests.JoinMatchRequest request) {
            return base.Channel.JoinMatchAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse LeaveMatch(GuessWhoCore.Contracts.Requests.LeaveMatchRequest request) {
            return base.Channel.LeaveMatch(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> LeaveMatchAsync(GuessWhoCore.Contracts.Requests.LeaveMatchRequest request) {
            return base.Channel.LeaveMatchAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse SetPlayerReadyStatus(GuessWhoCore.Contracts.Requests.SetPlayerReadyStatusRequest request) {
            return base.Channel.SetPlayerReadyStatus(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> SetPlayerReadyStatusAsync(GuessWhoCore.Contracts.Requests.SetPlayerReadyStatusRequest request) {
            return base.Channel.SetPlayerReadyStatusAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse SubscribeLobby(GuessWhoCore.Contracts.Requests.SubscribeLobbyRequest request) {
            return base.Channel.SubscribeLobby(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> SubscribeLobbyAsync(GuessWhoCore.Contracts.Requests.SubscribeLobbyRequest request) {
            return base.Channel.SubscribeLobbyAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse UnsubscribeLobby(GuessWhoCore.Contracts.Requests.UnsubscribeLobbyRequest request) {
            return base.Channel.UnsubscribeLobby(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> UnsubscribeLobbyAsync(GuessWhoCore.Contracts.Requests.UnsubscribeLobbyRequest request) {
            return base.Channel.UnsubscribeLobbyAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse StartMatch(GuessWhoCore.Contracts.Requests.StartMatchRequest request) {
            return base.Channel.StartMatch(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> StartMatchAsync(GuessWhoCore.Contracts.Requests.StartMatchRequest request) {
            return base.Channel.StartMatchAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse EndMatch(GuessWhoCore.Contracts.Requests.EndMatchRequest request) {
            return base.Channel.EndMatch(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> EndMatchAsync(GuessWhoCore.Contracts.Requests.EndMatchRequest request) {
            return base.Channel.EndMatchAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse ChooseSecretCharacter(GuessWhoCore.Contracts.Requests.ChooseSecretCharacterRequest request) {
            return base.Channel.ChooseSecretCharacter(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> ChooseSecretCharacterAsync(GuessWhoCore.Contracts.Requests.ChooseSecretCharacterRequest request) {
            return base.Channel.ChooseSecretCharacterAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.MatchDeckResponse GetMatchDeck(GuessWhoCore.Contracts.Requests.GetOrCreateMatchDeckRequest request) {
            return base.Channel.GetMatchDeck(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.MatchDeckResponse> GetMatchDeckAsync(GuessWhoCore.Contracts.Requests.GetOrCreateMatchDeckRequest request) {
            return base.Channel.GetMatchDeckAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse AskQuestion(GuessWhoCore.Contracts.Requests.AskQuestionRequest request) {
            return base.Channel.AskQuestion(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AskQuestionAsync(GuessWhoCore.Contracts.Requests.AskQuestionRequest request) {
            return base.Channel.AskQuestionAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse AnswerQuestion(GuessWhoCore.Contracts.Requests.AnswerQuestionRequest request) {
            return base.Channel.AnswerQuestion(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> AnswerQuestionAsync(GuessWhoCore.Contracts.Requests.AnswerQuestionRequest request) {
            return base.Channel.AnswerQuestionAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.PassTurnResponse PassTurn(GuessWhoCore.Contracts.Requests.PassTurnRequest request) {
            return base.Channel.PassTurn(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.PassTurnResponse> PassTurnAsync(GuessWhoCore.Contracts.Requests.PassTurnRequest request) {
            return base.Channel.PassTurnAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.ClaimTimeoutResponse ClaimTimeout(GuessWhoCore.Contracts.Requests.ClaimTimeoutRequest request) {
            return base.Channel.ClaimTimeout(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.ClaimTimeoutResponse> ClaimTimeoutAsync(GuessWhoCore.Contracts.Requests.ClaimTimeoutRequest request) {
            return base.Channel.ClaimTimeoutAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.FinalGuessResponse FinalGuess(GuessWhoCore.Contracts.Requests.FinalGuessRequest request) {
            return base.Channel.FinalGuess(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.FinalGuessResponse> FinalGuessAsync(GuessWhoCore.Contracts.Requests.FinalGuessRequest request) {
            return base.Channel.FinalGuessAsync(request);
        }
    }
}
