//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.UserServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceRef.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterUser", ReplyAction="http://tempuri.org/IUserService/RegisterUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUserService/RegisterUserServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.RegisterResponse RegisterUser(GuessWhoCore.Contracts.Requests.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterUser", ReplyAction="http://tempuri.org/IUserService/RegisterUserResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.RegisterResponse> RegisterUserAsync(GuessWhoCore.Contracts.Requests.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ConfirmEmailAddressWithVerificationCode", ReplyAction="http://tempuri.org/IUserService/ConfirmEmailAddressWithVerificationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUserService/ConfirmEmailAddressWithVerificationCodeServiceFau" +
            "ltFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.VerifyEmailResponse ConfirmEmailAddressWithVerificationCode(GuessWhoCore.Contracts.Requests.VerifyEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ConfirmEmailAddressWithVerificationCode", ReplyAction="http://tempuri.org/IUserService/ConfirmEmailAddressWithVerificationCodeResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.VerifyEmailResponse> ConfirmEmailAddressWithVerificationCodeAsync(GuessWhoCore.Contracts.Requests.VerifyEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ResendEmailVerificationCode", ReplyAction="http://tempuri.org/IUserService/ResendEmailVerificationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUserService/ResendEmailVerificationCodeServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        void ResendEmailVerificationCode(GuessWhoCore.Contracts.Requests.ResendVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ResendEmailVerificationCode", ReplyAction="http://tempuri.org/IUserService/ResendEmailVerificationCodeResponse")]
        System.Threading.Tasks.Task ResendEmailVerificationCodeAsync(GuessWhoCore.Contracts.Requests.ResendVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IUserService/SendPasswordRecoveryCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUserService/SendPasswordRecoveryCodeServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.PasswordRecoveryResponse SendPasswordRecoveryCode(GuessWhoCore.Contracts.Requests.PasswordRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendPasswordRecoveryCode", ReplyAction="http://tempuri.org/IUserService/SendPasswordRecoveryCodeResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.PasswordRecoveryResponse> SendPasswordRecoveryCodeAsync(GuessWhoCore.Contracts.Requests.PasswordRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdatePasswordWithVerificationCode", ReplyAction="http://tempuri.org/IUserService/UpdatePasswordWithVerificationCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUserService/UpdatePasswordWithVerificationCodeServiceFaultFau" +
            "lt", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        bool UpdatePasswordWithVerificationCode(GuessWhoCore.Contracts.Requests.UpdatePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdatePasswordWithVerificationCode", ReplyAction="http://tempuri.org/IUserService/UpdatePasswordWithVerificationCodeResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordWithVerificationCodeAsync(GuessWhoCore.Contracts.Requests.UpdatePasswordRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : GuessWhoClient.UserServiceRef.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<GuessWhoClient.UserServiceRef.IUserService>, GuessWhoClient.UserServiceRef.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.RegisterResponse RegisterUser(GuessWhoCore.Contracts.Requests.RegisterRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.RegisterResponse> RegisterUserAsync(GuessWhoCore.Contracts.Requests.RegisterRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.VerifyEmailResponse ConfirmEmailAddressWithVerificationCode(GuessWhoCore.Contracts.Requests.VerifyEmailRequest request) {
            return base.Channel.ConfirmEmailAddressWithVerificationCode(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.VerifyEmailResponse> ConfirmEmailAddressWithVerificationCodeAsync(GuessWhoCore.Contracts.Requests.VerifyEmailRequest request) {
            return base.Channel.ConfirmEmailAddressWithVerificationCodeAsync(request);
        }
        
        public void ResendEmailVerificationCode(GuessWhoCore.Contracts.Requests.ResendVerificationRequest request) {
            base.Channel.ResendEmailVerificationCode(request);
        }
        
        public System.Threading.Tasks.Task ResendEmailVerificationCodeAsync(GuessWhoCore.Contracts.Requests.ResendVerificationRequest request) {
            return base.Channel.ResendEmailVerificationCodeAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.PasswordRecoveryResponse SendPasswordRecoveryCode(GuessWhoCore.Contracts.Requests.PasswordRecoveryRequest request) {
            return base.Channel.SendPasswordRecoveryCode(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.PasswordRecoveryResponse> SendPasswordRecoveryCodeAsync(GuessWhoCore.Contracts.Requests.PasswordRecoveryRequest request) {
            return base.Channel.SendPasswordRecoveryCodeAsync(request);
        }
        
        public bool UpdatePasswordWithVerificationCode(GuessWhoCore.Contracts.Requests.UpdatePasswordRequest request) {
            return base.Channel.UpdatePasswordWithVerificationCode(request);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordWithVerificationCodeAsync(GuessWhoCore.Contracts.Requests.UpdatePasswordRequest request) {
            return base.Channel.UpdatePasswordWithVerificationCodeAsync(request);
        }
    }
}
