//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.UpdateServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateServiceRef.IUpdateProfileService")]
    public interface IUpdateProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/GetProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/GetProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUpdateProfileService/GetProfileServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.GetProfileResponse GetProfile(GuessWhoCore.Contracts.Requests.GetProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/GetProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/GetProfileResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetProfileResponse> GetProfileAsync(GuessWhoCore.Contracts.Requests.GetProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/UpdateUserProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/UpdateUserProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUpdateProfileService/UpdateUserProfileServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.UpdateProfileResponse UpdateUserProfile(GuessWhoCore.Contracts.Requests.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/UpdateUserProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.UpdateProfileResponse> UpdateUserProfileAsync(GuessWhoCore.Contracts.Requests.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/DeleteUserProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/DeleteUserProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GuessWhoCore.Contracts.Faults.ServiceFault), Action="http://tempuri.org/IUpdateProfileService/DeleteUserProfileServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/GuessWhoCore.Contracts.Faults")]
        GuessWhoCore.Contracts.Response.BasicResponse DeleteUserProfile(GuessWhoCore.Contracts.Requests.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUpdateProfileService/DeleteUserProfile", ReplyAction="http://tempuri.org/IUpdateProfileService/DeleteUserProfileResponse")]
        System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> DeleteUserProfileAsync(GuessWhoCore.Contracts.Requests.DeleteProfileRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateProfileServiceChannel : GuessWhoClient.UpdateServiceRef.IUpdateProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateProfileServiceClient : System.ServiceModel.ClientBase<GuessWhoClient.UpdateServiceRef.IUpdateProfileService>, GuessWhoClient.UpdateServiceRef.IUpdateProfileService {
        
        public UpdateProfileServiceClient() {
        }
        
        public UpdateProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GuessWhoCore.Contracts.Response.GetProfileResponse GetProfile(GuessWhoCore.Contracts.Requests.GetProfileRequest request) {
            return base.Channel.GetProfile(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.GetProfileResponse> GetProfileAsync(GuessWhoCore.Contracts.Requests.GetProfileRequest request) {
            return base.Channel.GetProfileAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.UpdateProfileResponse UpdateUserProfile(GuessWhoCore.Contracts.Requests.UpdateProfileRequest request) {
            return base.Channel.UpdateUserProfile(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.UpdateProfileResponse> UpdateUserProfileAsync(GuessWhoCore.Contracts.Requests.UpdateProfileRequest request) {
            return base.Channel.UpdateUserProfileAsync(request);
        }
        
        public GuessWhoCore.Contracts.Response.BasicResponse DeleteUserProfile(GuessWhoCore.Contracts.Requests.DeleteProfileRequest request) {
            return base.Channel.DeleteUserProfile(request);
        }
        
        public System.Threading.Tasks.Task<GuessWhoCore.Contracts.Response.BasicResponse> DeleteUserProfileAsync(GuessWhoCore.Contracts.Requests.DeleteProfileRequest request) {
            return base.Channel.DeleteUserProfileAsync(request);
        }
    }
}
